spring.application.name=spring-starter

spring.datasource.url=${URL_DB}
spring.datasource.username=${USERNAME_DB}
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=${DRIVER_DB:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.root=INFO
logging.level.org.springframework=WARN

app.security.jwt.secret=${JWT_SECRET}
app.security.jwt.access-expiration=${JWT_ACCESS_EXPIRATION:15m}
app.security.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:3h}
app.security.cookies.secure=${COOKIE_SECURE:true}

app.mail.host=${EMAIL_HOST}
app.mail.port=${EMAIL_PORT:587}
app.mail.username=${EMAIL_USERNAME}
app.mail.password=${EMAIL_PASSWORD}
app.mail.verification-base-url=${EMAIL_VERIFICATION_BASE_URL:http://localhost:8080}
app.mail.frontend-base-url=${FRONTEND_BASE_URL:http://localhost:5173}

app.init.superadmin.enabled=${INIT_SUPERADMIN_ENABLED:false}
app.init.superadmin.email=${INIT_SUPERADMIN_EMAIL:}
app.init.superadmin.password=${INIT_SUPERADMIN_PASSWORD:}
