spring.application.name=spring-starter

spring.datasource.url=${URL_DB}
spring.datasource.username=${USERNAME_DB}
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=${DRIVER_DB}
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.root=INFO
logging.level.org.springframework=WARN


app.security.jwt.secret=${JWT_SECRET}
app.security.jwt.access-expiration-minutes=${JWT_ACCESS_EXPIRATION_MINUTES:60}
app.security.jwt.refresh-expiration-hours=${JWT_REFRESH_EXPIRATION_HOURS:1}
app.security.jwt.refresh-expiration-minutes=${JWT_REFRESH_EXPIRATION_MINUTES:30}
app.security.enable-cors=${CORS_TRUE_OR_FALSE:true}
app.security.allowed-origins=${APP_SECURITY_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}


app.general.app-name=${APP_NAME:MiAplicacion}
app.general.version=${APP_VERSION:1.0.0}
app.general.timezone=${TIMEZONE:America/Argentina/Buenos_Aires}


spring.jpa.open-in-view=true


# Email
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_ID}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.verify.host=${VERIFY_EMAIL_HOST}
spring.mail.default-encoding=UTF-8



spring.mail.properties.mail.mime.charset=UTF-8
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.mail.admin=${EMAIL_ADMIN}

app.init.superadmin.enabled=${INIT_SUPERADMIN_ENABLED:false}
app.init.superadmin.email=${INIT_SUPERADMIN_EMAIL}
app.init.superadmin.password=${INIT_SUPERADMIN_PASSWORD}
app.init.seed-users.enabled=${INIT_SEED_USERS_ENABLED:false}
app.init.seed-users.file=${INIT_SEED_USERS_FILE:seed_users.json}


app.frontend-url=${URL_FRONT_BASE_LINK}