spring.application.name=spring-starter

# DB
spring.datasource.url=jdbc:h2:mem:starterdbtest;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Seguridad
app.security.jwt.secret=testsecretkeytestsecretkeytestsecretkey123456
app.security.jwt.access-expiration-minutes=15
app.security.jwt.refresh-expiration-hours=3
app.security.enable-cors=true
app.security.allowed-origins=http://localhost:5173

# Info general
app.general.app-name=SpringStarterTest
app.general.version=1.0.0-test
app.general.timezone=America/Argentina/Buenos_Aires

# Email
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=test
spring.mail.password=test
spring.mail.verify.host=http://localhost:8080
spring.mail.default-encoding=UTF-8

spring.mail.properties.mail.mime.charset=UTF-8
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.mail.admin=admin@test.com



# Logs
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

app.frontend-url=http://localhost:5173
