package com.ashenox.starter.shared.error;

public enum ApiErrorCode {
    VALIDATION_ERROR,
    AUTH_PASSWORD_CHANGE_REJECTED,
    AUTH_PASSWORD_CHANGE_RATE_LIMITED,
    MALFORMED_REQUEST,
    AUTH_INVALID_CREDENTIALS,
    AUTH_TOKEN_EXPIRED,
    AUTH_TOKEN_INVALID,
    AUTH_REFRESH_TOKEN_INVALID,
    AUTH_RESET_TOKEN_INVALID,
    AUTH_REQUIRED,
    CSRF_TOKEN_INVALID,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    METHOD_NOT_ALLOWED,
    RESOURCE_CONFLICT,
    INTERNAL_ERROR
}
